begin;

create extension if not exists pgcrypto with schema extensions;

alter table public.users add column if not exists email text;
alter table public.users add column if not exists password_hash text;
alter table public.users add column if not exists is_admin boolean not null default false;
alter table public.users add column if not exists failed_login_attempts integer not null default 0;
alter table public.users add column if not exists locked_until timestamptz;

create unique index if not exists users_username_lower_uidx on public.users (lower(btrim(username)));
create unique index if not exists users_email_lower_uidx on public.users (lower(btrim(email))) where email is not null;

update public.users
   set is_admin = (username = 'יהב')
 where is_admin is distinct from (username = 'יהב');

create table if not exists public.families (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(btrim(name)) between 1 and 80),
  invite_code text not null unique,
  created_by uuid not null references public.users(id) on delete restrict,
  legacy_owner_id uuid unique references public.users(id) on delete restrict,
  created_at timestamptz not null default now()
);

create table if not exists public.family_members (
  family_id uuid not null references public.families(id) on delete cascade,
  user_id uuid not null unique references public.users(id) on delete cascade,
  member_role text not null check (member_role in ('manager', 'shopper')),
  joined_at timestamptz not null default now(),
  primary key (family_id, user_id)
);

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid not null references public.users(id) on delete restrict,
  action text not null,
  entity_type text not null,
  entity_id text,
  previous_data jsonb,
  created_at timestamptz not null default now()
);

insert into public.families (name, invite_code, created_by, legacy_owner_id)
select
  'הבית של ' || u.username,
  upper(substr(replace(u.id::text, '-', ''), 1, 8)),
  u.id,
  u.id
from public.users u
where u.role::text = 'owner'
  and not exists (
    select 1 from public.families f where f.legacy_owner_id = u.id
  );

insert into public.family_members (family_id, user_id, member_role)
select f.id, u.id, 'manager'
from public.users u
join public.families f on f.legacy_owner_id = u.id
where u.role::text = 'owner'
on conflict (user_id) do nothing;

insert into public.family_members (family_id, user_id, member_role)
select f.id, shopper.id, 'shopper'
from public.users shopper
join public.families f on f.legacy_owner_id = shopper.shops_for_user_id
where shopper.role::text = 'shopper'
on conflict (user_id) do nothing;

alter table public.inventory add column if not exists family_id uuid references public.families(id);
alter table public.purchases add column if not exists family_id uuid references public.families(id);
alter table public.ratings add column if not exists family_id uuid references public.families(id);
alter table public.shopping_list add column if not exists family_id uuid references public.families(id);
alter table public.shopping_notes add column if not exists family_id uuid references public.families(id);
alter table public.imported_receipts add column if not exists family_id uuid references public.families(id);

update public.inventory as inv
   set family_id = f.id
  from public.families f
 where inv.family_id is null
   and f.legacy_owner_id = inv.owner_id;

update public.purchases as purchase_row
   set family_id = f.id
  from public.families f
 where purchase_row.family_id is null
   and f.legacy_owner_id = purchase_row.owner_id;

update public.ratings as rating_row
   set family_id = f.id
  from public.families f
 where rating_row.family_id is null
   and f.legacy_owner_id = rating_row.owner_id;

update public.shopping_list as list_row
   set family_id = f.id
  from public.families f
 where list_row.family_id is null
   and f.legacy_owner_id = list_row.owner_id;

update public.shopping_notes as note_row
   set family_id = f.id
  from public.families f
 where note_row.family_id is null
   and f.legacy_owner_id = note_row.owner_id;

update public.imported_receipts as receipt_row
   set family_id = f.id
  from public.families f
 where receipt_row.family_id is null
   and f.legacy_owner_id = (
     select id from public.users where username = 'יהב' limit 1
   );

create index if not exists inventory_family_idx on public.inventory (family_id);
create index if not exists purchases_family_idx on public.purchases (family_id, purchased_at desc);
create index if not exists ratings_family_idx on public.ratings (family_id);
create index if not exists shopping_list_family_idx on public.shopping_list (family_id, added_at desc);
create index if not exists shopping_notes_family_idx on public.shopping_notes (family_id, created_at desc);
create index if not exists imported_receipts_family_idx on public.imported_receipts (family_id);

alter table public.foods add column if not exists category text;
alter table public.foods add column if not exists created_by uuid references public.users(id) on delete set null;
alter table public.foods add column if not exists created_at timestamptz not null default now();

update public.foods
   set created_by = (select id from public.users where username = 'יהב' limit 1)
 where created_by is null;

create schema if not exists app_private;
revoke all on schema app_private from public, anon, authenticated;

create or replace function app_private.session_context(p_session_token text)
returns table (
  user_id uuid,
  username text,
  app_role text,
  is_admin boolean,
  family_id uuid,
  family_name text,
  member_role text,
  anchor_owner_id uuid,
  expires_at timestamptz,
  needs_password_setup boolean
)
language plpgsql
security definer
set search_path = public, app_private, extensions
as $$
begin
  return query
  select
    u.id,
    u.username::text,
    u.role::text,
    u.is_admin,
    fm.family_id,
    f.name::text,
    fm.member_role::text,
    f.created_by,
    s.expires_at,
    (u.password_hash is null)
  from public.sessions s
  join public.users u on u.id = s.user_id
  left join public.family_members fm on fm.user_id = u.id
  left join public.families f on f.id = fm.family_id
  where s.token::text = p_session_token
    and s.expires_at > now()
  limit 1;

  if not found then
    raise exception 'Invalid or expired session' using errcode = '42501';
  end if;
end;
$$;

revoke all on function app_private.session_context(text) from public, anon, authenticated;

create or replace function public.get_app_session(p_session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, app_private, extensions
as $$
declare
  ctx record;
begin
  select * into ctx from app_private.session_context(p_session_token);
  return jsonb_build_object(
    'token', p_session_token,
    'expires_at', ctx.expires_at,
    'user_id', ctx.user_id,
    'username', ctx.username,
    'role', ctx.app_role,
    'is_admin', ctx.is_admin,
    'family_id', ctx.family_id,
    'family_name', ctx.family_name,
    'member_role', ctx.member_role,
    'owner_id', ctx.anchor_owner_id,
    'needs_password_setup', ctx.needs_password_setup
  );
exception when sqlstate '42501' then
  return jsonb_build_object('error', 'SESSION_EXPIRED');
end;
$$;

create or replace function public.claim_legacy_account(
  p_session_token text,
  p_email text,
  p_password text
)
returns jsonb
language plpgsql
security definer
set search_path = public, app_private, extensions
as $$
declare
  ctx record;
  clean_email text := lower(btrim(coalesce(p_email, '')));
begin
  select * into ctx from app_private.session_context(p_session_token);

  if not ctx.needs_password_setup then
    return jsonb_build_object('error', 'ALREADY_CONFIGURED');
  end if;
  if clean_email !~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then
    return jsonb_build_object('error', 'INVALID_EMAIL');
  end if;
  if char_length(coalesce(p_password, '')) < 8 then
    return jsonb_build_object('error', 'WEAK_PASSWORD');
  end if;
  if ctx.is_admin and clean_email <> 'yahavalon76@gmail.com' then
    return jsonb_build_object('error', 'ADMIN_EMAIL_MISMATCH');
  end if;
  if exists (select 1 from public.users where lower(email) = clean_email and id <> ctx.user_id) then
    return jsonb_build_object('error', 'EMAIL_TAKEN');
  end if;

  update public.users
     set email = clean_email,
         password_hash = crypt(p_password, gen_salt('bf', 12)),
         failed_login_attempts = 0,
         locked_until = null
   where id = ctx.user_id;

  update public.sessions
     set expires_at = now() + interval '7 days'
   where token::text = p_session_token;

  return public.get_app_session(p_session_token);
end;
$$;

create or replace function public.register_app_user(
  p_username text,
  p_email text,
  p_password text,
  p_role text,
  p_family_name text default null,
  p_invite_code text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, app_private, extensions
as $$
declare
  clean_username text := btrim(coalesce(p_username, ''));
  clean_email text := lower(btrim(coalesce(p_email, '')));
  clean_role text := lower(btrim(coalesce(p_role, '')));
  new_user_id uuid := gen_random_uuid();
  target_family_id uuid;
  target_owner_id uuid;
  new_token uuid := gen_random_uuid();
  new_expiry timestamptz := now() + interval '7 days';
  next_invite_code text;
begin
  if char_length(clean_username) not between 2 and 40 then
    return jsonb_build_object('error', 'INVALID_USERNAME');
  end if;
  if clean_email !~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then
    return jsonb_build_object('error', 'INVALID_EMAIL');
  end if;
  if char_length(coalesce(p_password, '')) < 8 then
    return jsonb_build_object('error', 'WEAK_PASSWORD');
  end if;
  if clean_role not in ('owner', 'shopper') then
    return jsonb_build_object('error', 'INVALID_ROLE');
  end if;
  if exists (select 1 from public.users where lower(btrim(username)) = lower(clean_username)) then
    return jsonb_build_object('error', 'USERNAME_TAKEN');
  end if;
  if exists (select 1 from public.users where lower(email) = clean_email) then
    return jsonb_build_object('error', 'EMAIL_TAKEN');
  end if;

  if clean_role = 'owner' then
    if char_length(btrim(coalesce(p_family_name, ''))) not between 1 and 80 then
      return jsonb_build_object('error', 'FAMILY_NAME_REQUIRED');
    end if;
  else
    select f.id, f.created_by
      into target_family_id, target_owner_id
      from public.families f
     where upper(f.invite_code) = upper(btrim(coalesce(p_invite_code, '')));
    if not found then
      return jsonb_build_object('error', 'INVALID_INVITE');
    end if;
  end if;

  insert into public.users (id, username, email, password_hash, role, shops_for_user_id, is_admin)
  values (
    new_user_id,
    clean_username,
    clean_email,
    crypt(p_password, gen_salt('bf', 12)),
    clean_role,
    case when clean_role = 'shopper' then target_owner_id else null end,
    false
  );

  if clean_role = 'owner' then
    next_invite_code := upper(substr(md5(gen_random_uuid()::text || clock_timestamp()::text), 1, 8));
    insert into public.families (name, invite_code, created_by, legacy_owner_id)
    values (btrim(p_family_name), next_invite_code, new_user_id, new_user_id)
    returning id into target_family_id;
    insert into public.family_members (family_id, user_id, member_role)
    values (target_family_id, new_user_id, 'manager');
  else
    insert into public.family_members (family_id, user_id, member_role)
    values (target_family_id, new_user_id, 'shopper');
  end if;

  insert into public.sessions (token, user_id, expires_at)
  values (new_token, new_user_id, new_expiry);

  return public.get_app_session(new_token::text);
exception when unique_violation then
  return jsonb_build_object('error', 'ACCOUNT_EXISTS');
end;
$$;

create or replace function public.login_app_user(p_username text, p_password text)
returns jsonb
language plpgsql
security definer
set search_path = public, app_private, extensions
as $$
declare
  matched_user public.users%rowtype;
  next_attempts integer;
  new_token uuid := gen_random_uuid();
  new_expiry timestamptz := now() + interval '7 days';
begin
  select * into matched_user
    from public.users
   where lower(btrim(username)) = lower(btrim(coalesce(p_username, '')))
   for update;

  if not found or matched_user.password_hash is null then
    return jsonb_build_object('error', 'INVALID_CREDENTIALS');
  end if;
  if matched_user.locked_until is not null and matched_user.locked_until > now() then
    return jsonb_build_object('error', 'ACCOUNT_LOCKED');
  end if;
  if crypt(coalesce(p_password, ''), matched_user.password_hash) <> matched_user.password_hash then
    next_attempts := matched_user.failed_login_attempts + 1;
    update public.users
       set failed_login_attempts = next_attempts,
           locked_until = case when next_attempts >= 5 then now() + interval '15 minutes' else null end
     where id = matched_user.id;
    return jsonb_build_object('error', case when next_attempts >= 5 then 'ACCOUNT_LOCKED' else 'INVALID_CREDENTIALS' end);
  end if;

  update public.users
     set failed_login_attempts = 0, locked_until = null
   where id = matched_user.id;
  delete from public.sessions where user_id = matched_user.id and expires_at <= now();
  insert into public.sessions (token, user_id, expires_at)
  values (new_token, matched_user.id, new_expiry);

  return public.get_app_session(new_token::text);
end;
$$;

create or replace function public.logout_app_user(p_session_token text)
returns boolean
language sql
security definer
set search_path = public
as $$
  delete from public.sessions where token::text = p_session_token returning true;
$$;

create or replace function public.get_family_details(p_session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, app_private
as $$
declare
  ctx record;
  invite text;
begin
  select * into ctx from app_private.session_context(p_session_token);
  select invite_code into invite from public.families where id = ctx.family_id;
  return jsonb_build_object(
    'id', ctx.family_id,
    'name', ctx.family_name,
    'member_role', ctx.member_role,
    'invite_code', case when ctx.member_role = 'manager' or ctx.is_admin then invite else null end
  );
end;
$$;

create or replace function public.add_catalog_food(
  p_session_token text,
  p_name text,
  p_manufacturer text,
  p_category text,
  p_unit_qty text,
  p_picture_url text
)
returns jsonb
language plpgsql
security definer
set search_path = public, app_private
as $$
declare
  ctx record;
  new_food public.foods%rowtype;
begin
  select * into ctx from app_private.session_context(p_session_token);
  if ctx.member_role <> 'manager' and not ctx.is_admin then
    raise exception 'Only household managers can add products' using errcode = '42501';
  end if;
  if char_length(btrim(coalesce(p_name, ''))) = 0
     or char_length(btrim(coalesce(p_manufacturer, ''))) = 0
     or char_length(btrim(coalesce(p_category, ''))) = 0
     or char_length(btrim(coalesce(p_unit_qty, ''))) = 0
     or char_length(btrim(coalesce(p_picture_url, ''))) = 0 then
    raise exception 'All product fields are required' using errcode = '22023';
  end if;
  if exists (
    select 1 from public.foods
     where lower(btrim(name)) = lower(btrim(p_name))
       and lower(btrim(coalesce(manufacturer, ''))) = lower(btrim(p_manufacturer))
       and lower(btrim(coalesce(unit_qty, ''))) = lower(btrim(p_unit_qty))
  ) then
    raise exception 'Product already exists' using errcode = '23505';
  end if;

  insert into public.foods (
    source, external_id, name, manufacturer, unit_qty, picture_url,
    category, created_by, updated_at
  )
  values (
    'manual', 'manual_' || replace(gen_random_uuid()::text, '-', ''),
    btrim(p_name), btrim(p_manufacturer), btrim(p_unit_qty), btrim(p_picture_url),
    btrim(p_category), ctx.user_id, now()
  )
  returning * into new_food;

  return to_jsonb(new_food);
end;
$$;

create or replace function public.update_catalog_food(
  p_session_token text,
  p_food_id uuid,
  p_name text,
  p_manufacturer text,
  p_category text,
  p_unit_qty text,
  p_picture_url text
)
returns jsonb
language plpgsql
security definer
set search_path = public, app_private
as $$
declare
  ctx record;
  existing_food public.foods%rowtype;
begin
  select * into ctx from app_private.session_context(p_session_token);
  select * into existing_food from public.foods where id = p_food_id;
  if not found then
    raise exception 'Product not found' using errcode = 'P0002';
  end if;
  if not ctx.is_admin and existing_food.created_by is distinct from ctx.user_id then
    raise exception 'You can edit only products you added' using errcode = '42501';
  end if;
  if char_length(btrim(coalesce(p_name, ''))) = 0
     or char_length(btrim(coalesce(p_manufacturer, ''))) = 0
     or char_length(btrim(coalesce(p_category, ''))) = 0
     or char_length(btrim(coalesce(p_unit_qty, ''))) = 0
     or char_length(btrim(coalesce(p_picture_url, ''))) = 0 then
    raise exception 'All product fields are required' using errcode = '22023';
  end if;

  update public.foods
     set name = btrim(p_name),
         manufacturer = btrim(p_manufacturer),
         category = btrim(p_category),
         unit_qty = btrim(p_unit_qty),
         picture_url = btrim(p_picture_url),
         updated_at = now()
   where id = p_food_id
   returning * into existing_food;
  return to_jsonb(existing_food);
end;
$$;

create or replace function public.add_receipt_catalog_food(
  p_session_token text,
  p_external_id text,
  p_name text,
  p_manufacturer text,
  p_category text,
  p_unit_qty text,
  p_picture_url text
)
returns jsonb
language plpgsql
security definer
set search_path = public, app_private
as $$
declare
  ctx record;
  saved_food public.foods%rowtype;
  clean_external_id text := nullif(btrim(coalesce(p_external_id, '')), '');
begin
  select * into ctx from app_private.session_context(p_session_token);
  if ctx.member_role <> 'manager' and not ctx.is_admin then
    raise exception 'Only household managers can import receipt products' using errcode = '42501';
  end if;
  if char_length(btrim(coalesce(p_name, ''))) = 0
     or char_length(btrim(coalesce(p_manufacturer, ''))) = 0
     or char_length(btrim(coalesce(p_category, ''))) = 0
     or char_length(btrim(coalesce(p_unit_qty, ''))) = 0 then
    raise exception 'Receipt product data is incomplete' using errcode = '22023';
  end if;

  select * into saved_food
    from public.foods
   where (clean_external_id is not null and external_id = clean_external_id)
      or (
        lower(btrim(name)) = lower(btrim(p_name))
        and lower(btrim(coalesce(manufacturer, ''))) = lower(btrim(p_manufacturer))
        and lower(btrim(coalesce(unit_qty, ''))) = lower(btrim(p_unit_qty))
      )
   order by case when external_id = clean_external_id then 0 else 1 end
   limit 1;
  if found then
    return to_jsonb(saved_food);
  end if;

  insert into public.foods (
    source, external_id, name, manufacturer, unit_qty, picture_url,
    category, created_by, updated_at
  )
  values (
    'receipt',
    coalesce(clean_external_id, 'receipt_' || replace(gen_random_uuid()::text, '-', '')),
    btrim(p_name), btrim(p_manufacturer), btrim(p_unit_qty),
    coalesce(nullif(btrim(coalesce(p_picture_url, '')), ''), '/groceries-app/product-placeholder.svg'),
    btrim(p_category), ctx.user_id, now()
  )
  returning * into saved_food;
  return to_jsonb(saved_food);
end;
$$;

create or replace function public.delete_catalog_food(p_session_token text, p_food_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public, app_private
as $$
declare
  ctx record;
  deleted_food public.foods%rowtype;
begin
  select * into ctx from app_private.session_context(p_session_token);
  if not ctx.is_admin then
    raise exception 'Only the administrator can delete products' using errcode = '42501';
  end if;
  select * into deleted_food from public.foods where id = p_food_id;
  if not found then
    return false;
  end if;
  delete from public.foods where id = p_food_id;
  insert into public.admin_audit_log (actor_user_id, action, entity_type, entity_id, previous_data)
  values (ctx.user_id, 'delete', 'food', p_food_id::text, to_jsonb(deleted_food));
  return true;
end;
$$;

revoke all on function public.get_app_session(text) from public;
revoke all on function public.claim_legacy_account(text, text, text) from public;
revoke all on function public.register_app_user(text, text, text, text, text, text) from public;
revoke all on function public.login_app_user(text, text) from public;
revoke all on function public.logout_app_user(text) from public;
revoke all on function public.get_family_details(text) from public;
revoke all on function public.add_catalog_food(text, text, text, text, text, text) from public;
revoke all on function public.update_catalog_food(text, uuid, text, text, text, text, text) from public;
revoke all on function public.add_receipt_catalog_food(text, text, text, text, text, text, text) from public;
revoke all on function public.delete_catalog_food(text, uuid) from public;

grant execute on function public.get_app_session(text) to anon, authenticated;
grant execute on function public.claim_legacy_account(text, text, text) to anon, authenticated;
grant execute on function public.register_app_user(text, text, text, text, text, text) to anon, authenticated;
grant execute on function public.login_app_user(text, text) to anon, authenticated;
grant execute on function public.logout_app_user(text) to anon, authenticated;
grant execute on function public.get_family_details(text) to anon, authenticated;
grant execute on function public.add_catalog_food(text, text, text, text, text, text) to anon, authenticated;
grant execute on function public.update_catalog_food(text, uuid, text, text, text, text, text) to anon, authenticated;
grant execute on function public.add_receipt_catalog_food(text, text, text, text, text, text, text) to anon, authenticated;
grant execute on function public.delete_catalog_food(text, uuid) to anon, authenticated;

commit;
