begin;

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  family_id uuid not null references public.families(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists push_subscriptions_family_user_idx
  on public.push_subscriptions (family_id, user_id);

create or replace function public.save_push_subscription(
  p_session_token text,
  p_endpoint text,
  p_p256dh text,
  p_auth text,
  p_user_agent text default null
)
returns boolean
language plpgsql
security definer
set search_path = public, app_private
as $$
declare
  ctx record;
  clean_endpoint text := btrim(coalesce(p_endpoint, ''));
  clean_p256dh text := btrim(coalesce(p_p256dh, ''));
  clean_auth text := btrim(coalesce(p_auth, ''));
begin
  select * into ctx from app_private.session_context(p_session_token);
  if ctx.family_id is null then
    raise exception 'User is not assigned to a family' using errcode = '42501';
  end if;
  if clean_endpoint !~ '^https://' or char_length(clean_endpoint) > 2048 then
    raise exception 'Invalid push endpoint' using errcode = '22023';
  end if;
  if char_length(clean_p256dh) not between 20 and 512
     or char_length(clean_auth) not between 8 and 256 then
    raise exception 'Invalid push keys' using errcode = '22023';
  end if;

  insert into public.push_subscriptions (
    user_id, family_id, endpoint, p256dh, auth, user_agent, updated_at
  )
  values (
    ctx.user_id, ctx.family_id, clean_endpoint, clean_p256dh, clean_auth,
    left(p_user_agent, 500), now()
  )
  on conflict (endpoint) do update set
    user_id = excluded.user_id,
    family_id = excluded.family_id,
    p256dh = excluded.p256dh,
    auth = excluded.auth,
    user_agent = excluded.user_agent,
    updated_at = now();
  return true;
end;
$$;

create or replace function public.delete_push_subscription(
  p_session_token text,
  p_endpoint text
)
returns boolean
language plpgsql
security definer
set search_path = public, app_private
as $$
declare
  ctx record;
begin
  select * into ctx from app_private.session_context(p_session_token);
  delete from public.push_subscriptions
   where user_id = ctx.user_id and endpoint = btrim(coalesce(p_endpoint, ''));
  return found;
end;
$$;

alter table public.push_subscriptions enable row level security;
revoke all on public.push_subscriptions from anon, authenticated;

revoke all on function public.save_push_subscription(text, text, text, text, text) from public;
revoke all on function public.delete_push_subscription(text, text) from public;
grant execute on function public.save_push_subscription(text, text, text, text, text) to anon, authenticated;
grant execute on function public.delete_push_subscription(text, text) to anon, authenticated;
grant execute on function public.get_app_session(text) to service_role;
grant select, delete on public.push_subscriptions to service_role;
grant select on public.family_members, public.shopping_list, public.purchases, public.foods to service_role;

commit;
