begin;

create table if not exists public.recipe_suggestions (
  id uuid primary key default gen_random_uuid(),
  family_id uuid not null references public.families(id) on delete cascade,
  external_key text not null,
  title text not null,
  source_name text not null,
  source_url text not null,
  rating numeric not null check (rating >= 4 and rating <= 5),
  reviews integer not null default 0 check (reviews >= 0),
  total_time_minutes integer not null check (total_time_minutes > 0),
  image_url text,
  servings numeric,
  ingredients jsonb not null default '[]'::jsonb check (jsonb_typeof(ingredients) = 'array'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (family_id, external_key)
);

create index if not exists recipe_suggestions_family_updated_idx
  on public.recipe_suggestions (family_id, updated_at desc);

create table if not exists public.recipe_selections (
  id bigint generated by default as identity primary key,
  family_id uuid not null references public.families(id) on delete cascade,
  recipe_id uuid references public.recipe_suggestions(id) on delete set null,
  recipe_title text not null,
  selected_by uuid references public.users(id) on delete set null,
  deductions jsonb not null default '[]'::jsonb,
  selected_at timestamptz not null default now()
);

create index if not exists recipe_selections_family_date_idx
  on public.recipe_selections (family_id, selected_at desc);

alter table public.recipe_suggestions enable row level security;
alter table public.recipe_selections enable row level security;
revoke all on public.recipe_suggestions, public.recipe_selections from anon, authenticated;

create or replace function public.get_recipe_inventory_context(p_session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, app_private
as $$
declare
  ctx record;
begin
  select * into ctx from app_private.session_context(p_session_token);
  if ctx.family_id is null then
    raise exception 'User is not assigned to a family' using errcode = '42501';
  end if;

  return coalesce((
    select jsonb_agg(jsonb_build_object(
      'food_id', f.id,
      'name', f.name,
      'manufacturer', f.manufacturer,
      'unit_qty', f.unit_qty,
      'category', f.category,
      'quantity', inv.quantity
    ) order by inv.quantity desc, f.name)
    from public.inventory inv
    join public.foods f on f.id = inv.food_id
    where inv.family_id = ctx.family_id and inv.quantity > 0
  ), '[]'::jsonb);
end;
$$;

create or replace function public.cache_family_recipe_suggestions(
  p_session_token text,
  p_recipes jsonb
)
returns integer
language plpgsql
security definer
set search_path = public, app_private
as $$
declare
  ctx record;
  recipe jsonb;
  saved_count integer := 0;
  clean_rating numeric;
  clean_time integer;
  clean_url text;
begin
  select * into ctx from app_private.session_context(p_session_token);
  if ctx.family_id is null then
    raise exception 'User is not assigned to a family' using errcode = '42501';
  end if;
  if jsonb_typeof(coalesce(p_recipes, '[]'::jsonb)) <> 'array'
     or jsonb_array_length(coalesce(p_recipes, '[]'::jsonb)) > 12 then
    raise exception 'Invalid recipe cache payload' using errcode = '22023';
  end if;

  for recipe in select value from jsonb_array_elements(coalesce(p_recipes, '[]'::jsonb))
  loop
    clean_rating := nullif(recipe->>'rating', '')::numeric;
    clean_time := nullif(recipe->>'total_time_minutes', '')::integer;
    clean_url := btrim(coalesce(recipe->>'source_url', ''));
    if char_length(btrim(coalesce(recipe->>'external_key', ''))) = 0
       or char_length(btrim(coalesce(recipe->>'title', ''))) = 0
       or clean_rating < 4 or clean_rating > 5
       or clean_time <= 0
       or clean_url !~ '^https://'
       or jsonb_typeof(coalesce(recipe->'ingredients', '[]'::jsonb)) <> 'array'
       or jsonb_array_length(coalesce(recipe->'ingredients', '[]'::jsonb)) > 40 then
      continue;
    end if;

    insert into public.recipe_suggestions (
      family_id, external_key, title, source_name, source_url, rating, reviews,
      total_time_minutes, image_url, servings, ingredients, updated_at
    ) values (
      ctx.family_id,
      left(btrim(recipe->>'external_key'), 300),
      left(btrim(recipe->>'title'), 300),
      left(coalesce(nullif(btrim(recipe->>'source_name'), ''), 'מקור המתכון'), 200),
      left(clean_url, 2000),
      clean_rating,
      greatest(0, coalesce(nullif(recipe->>'reviews', '')::integer, 0)),
      clean_time,
      nullif(left(btrim(coalesce(recipe->>'image_url', '')), 2000), ''),
      nullif(recipe->>'servings', '')::numeric,
      recipe->'ingredients',
      now()
    )
    on conflict (family_id, external_key) do update set
      title = excluded.title,
      source_name = excluded.source_name,
      source_url = excluded.source_url,
      rating = excluded.rating,
      reviews = excluded.reviews,
      total_time_minutes = excluded.total_time_minutes,
      image_url = excluded.image_url,
      servings = excluded.servings,
      ingredients = excluded.ingredients,
      updated_at = now();
    saved_count := saved_count + 1;
  end loop;

  delete from public.recipe_suggestions
   where family_id = ctx.family_id and updated_at < now() - interval '30 days';
  return saved_count;
end;
$$;

create or replace function public.list_family_recipe_suggestions(p_session_token text)
returns setof public.recipe_suggestions
language plpgsql
security definer
set search_path = public, app_private
as $$
declare
  ctx record;
begin
  select * into ctx from app_private.session_context(p_session_token);
  if ctx.family_id is null then
    raise exception 'User is not assigned to a family' using errcode = '42501';
  end if;
  return query
    select recipe.* from public.recipe_suggestions recipe
     where recipe.family_id = ctx.family_id
       and recipe.updated_at >= now() - interval '30 days'
     order by recipe.rating desc, recipe.reviews desc, recipe.updated_at desc
     limit 12;
end;
$$;

create or replace function public.choose_family_recipe(
  p_session_token text,
  p_recipe_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public, app_private
as $$
declare
  ctx record;
  chosen public.recipe_suggestions%rowtype;
  ingredient jsonb;
  requirement record;
  requested_food_id uuid;
  required_quantity numeric;
  available_quantity numeric;
  requested_name text;
  deductions jsonb := '[]'::jsonb;
  required_by_food jsonb := '{}'::jsonb;
  deducted_count integer := 0;
begin
  select * into ctx from app_private.session_context(p_session_token);
  if ctx.family_id is null then
    raise exception 'User is not assigned to a family' using errcode = '42501';
  end if;

  select * into chosen from public.recipe_suggestions
   where id = p_recipe_id and family_id = ctx.family_id;
  if not found then return jsonb_build_object('error', 'RECIPE_NOT_FOUND'); end if;

  for ingredient in select value from jsonb_array_elements(chosen.ingredients)
  loop
    if coalesce((ingredient->>'optional')::boolean, false) then continue; end if;
    begin
      requested_food_id := nullif(ingredient->>'food_id', '')::uuid;
      required_quantity := nullif(ingredient->>'inventory_quantity_required', '')::numeric;
    exception when others then
      return jsonb_build_object('error', 'INVALID_INGREDIENT', 'ingredient', ingredient->>'name');
    end;
    if requested_food_id is null or required_quantity is null or required_quantity <= 0 then
      return jsonb_build_object('error', 'MISSING_INGREDIENT', 'ingredient', ingredient->>'name');
    end if;

    required_by_food := jsonb_set(
      required_by_food,
      array[requested_food_id::text],
      to_jsonb(coalesce((required_by_food->>requested_food_id::text)::numeric, 0) + required_quantity),
      true
    );
    deductions := deductions || jsonb_build_array(jsonb_build_object(
      'food_id', requested_food_id,
      'name', ingredient->>'name',
      'quantity', required_quantity,
      'required_text', ingredient->>'required_text'
    ));
  end loop;

  for requirement in select key, value from jsonb_each_text(required_by_food)
  loop
    requested_food_id := requirement.key::uuid;
    required_quantity := requirement.value::numeric;
    select inv.quantity, f.name into available_quantity, requested_name
      from public.inventory inv
      join public.foods f on f.id = inv.food_id
     where inv.family_id = ctx.family_id and inv.food_id = requested_food_id
     for update;
    if coalesce(available_quantity, 0) < required_quantity then
      return jsonb_build_object(
        'error', 'INSUFFICIENT_INGREDIENT',
        'ingredient', coalesce(requested_name, 'מרכיב חסר'),
        'available', coalesce(available_quantity, 0),
        'required', required_quantity
      );
    end if;
  end loop;

  for requirement in select key, value from jsonb_each_text(required_by_food)
  loop
    requested_food_id := requirement.key::uuid;
    required_quantity := requirement.value::numeric;

    update public.inventory
       set quantity = quantity - required_quantity
     where family_id = ctx.family_id and food_id = requested_food_id;
    delete from public.inventory
     where family_id = ctx.family_id and food_id = requested_food_id and quantity <= 0.000001;
    deducted_count := deducted_count + 1;
  end loop;

  insert into public.recipe_selections (
    family_id, recipe_id, recipe_title, selected_by, deductions
  ) values (
    ctx.family_id, chosen.id, chosen.title, ctx.user_id, deductions
  );

  return jsonb_build_object(
    'success', true,
    'recipe_title', chosen.title,
    'deducted_count', deducted_count
  );
end;
$$;

revoke all on function public.get_recipe_inventory_context(text) from public;
revoke all on function public.cache_family_recipe_suggestions(text, jsonb) from public;
revoke all on function public.list_family_recipe_suggestions(text) from public;
revoke all on function public.choose_family_recipe(text, uuid) from public;
grant execute on function public.get_recipe_inventory_context(text) to anon, authenticated;
grant execute on function public.cache_family_recipe_suggestions(text, jsonb) to anon, authenticated;
grant execute on function public.list_family_recipe_suggestions(text) to anon, authenticated;
grant execute on function public.choose_family_recipe(text, uuid) to anon, authenticated;

commit;
