begin;

create table if not exists public.inventory_additions (
  id bigint generated by default as identity primary key,
  family_id uuid not null references public.families(id) on delete cascade,
  food_id uuid not null references public.foods(id) on delete cascade,
  quantity numeric not null check (quantity > 0),
  added_at timestamptz not null default now(),
  added_by uuid references public.users(id) on delete set null,
  source text not null default 'direct',
  source_ref text
);

create index if not exists inventory_additions_family_food_date_idx
  on public.inventory_additions (family_id, food_id, added_at);
create unique index if not exists inventory_additions_source_ref_uidx
  on public.inventory_additions (source, source_ref)
  where source_ref is not null;

insert into public.inventory_additions (
  family_id, food_id, quantity, added_at, added_by, source, source_ref
)
select
  p.family_id,
  p.food_id,
  p.quantity,
  p.purchased_at,
  p.shopper_id,
  'purchase',
  md5(concat_ws('|', p.family_id::text, p.food_id::text, p.purchased_at::text, p.quantity::text, p.shopper_id::text))
from public.purchases p
where p.quantity > 0
on conflict do nothing;

insert into public.inventory_additions (
  family_id, food_id, quantity, added_at, source, source_ref
)
select
  inv.family_id,
  inv.food_id,
  inv.quantity - coalesce(history.total_added, 0),
  now(),
  'existing',
  'inventory:' || inv.family_id::text || ':' || inv.food_id::text
from public.inventory inv
left join (
  select family_id, food_id, sum(quantity) as total_added
    from public.inventory_additions
   group by family_id, food_id
) history on history.family_id = inv.family_id and history.food_id = inv.food_id
where inv.quantity > coalesce(history.total_added, 0)
on conflict do nothing;

create or replace function public.list_family_inventory_additions(p_session_token text)
returns table (
  id bigint,
  food_id uuid,
  quantity numeric,
  added_at timestamptz,
  source text
)
language plpgsql
security definer
set search_path = public, app_private
as $$
declare
  ctx record;
begin
  select * into ctx from app_private.session_context(p_session_token);
  return query
    select ia.id, ia.food_id, ia.quantity, ia.added_at, ia.source
      from public.inventory_additions ia
     where ia.family_id = ctx.family_id
     order by ia.added_at, ia.id;
end;
$$;

create or replace function public.set_family_inventory_quantity(
  p_session_token text,
  p_food_id uuid,
  p_quantity numeric
)
returns numeric
language plpgsql
security definer
set search_path = public, app_private
as $$
declare
  ctx record;
  clean_quantity numeric := greatest(0, coalesce(p_quantity, 0));
  previous_quantity numeric := 0;
begin
  select * into ctx from app_private.session_context(p_session_token);
  if ctx.family_id is null then
    raise exception 'User is not assigned to a family' using errcode = '42501';
  end if;

  select coalesce(quantity, 0) into previous_quantity
    from public.inventory
   where family_id = ctx.family_id and food_id = p_food_id;
  previous_quantity := coalesce(previous_quantity, 0);

  if clean_quantity = 0 then
    delete from public.inventory
     where family_id = ctx.family_id and food_id = p_food_id;
  else
    insert into public.inventory (owner_id, family_id, food_id, quantity)
    values (ctx.anchor_owner_id, ctx.family_id, p_food_id, clean_quantity)
    on conflict (owner_id, food_id)
    do update set quantity = excluded.quantity, family_id = excluded.family_id;
  end if;

  if clean_quantity > previous_quantity then
    insert into public.inventory_additions (family_id, food_id, quantity, added_by, source)
    values (ctx.family_id, p_food_id, clean_quantity - previous_quantity, ctx.user_id, 'adjustment');
  end if;
  return clean_quantity;
end;
$$;

create or replace function public.add_family_inventory_items(
  p_session_token text,
  p_items jsonb
)
returns integer
language plpgsql
security definer
set search_path = public, app_private
as $$
declare
  ctx record;
  item record;
  added_count integer := 0;
begin
  select * into ctx from app_private.session_context(p_session_token);
  if ctx.family_id is null then
    raise exception 'User is not assigned to a family' using errcode = '42501';
  end if;

  for item in
    select value->>'food_id' as food_id, (value->>'quantity')::numeric as quantity
      from jsonb_array_elements(coalesce(p_items, '[]'::jsonb))
  loop
    if item.food_id is null or coalesce(item.quantity, 0) <= 0 then
      continue;
    end if;
    insert into public.inventory (owner_id, family_id, food_id, quantity)
    values (ctx.anchor_owner_id, ctx.family_id, item.food_id::uuid, item.quantity)
    on conflict (owner_id, food_id)
    do update set
      quantity = public.inventory.quantity + excluded.quantity,
      family_id = excluded.family_id;
    insert into public.inventory_additions (family_id, food_id, quantity, added_by, source)
    values (ctx.family_id, item.food_id::uuid, item.quantity, ctx.user_id, 'direct');
    added_count := added_count + 1;
  end loop;
  return added_count;
end;
$$;

create or replace function public.finish_family_shopping(p_session_token text)
returns integer
language plpgsql
security definer
set search_path = public, app_private
as $$
declare
  ctx record;
  purchased_count integer := 0;
begin
  select * into ctx from app_private.session_context(p_session_token);

  insert into public.inventory (owner_id, family_id, food_id, quantity)
  select ctx.anchor_owner_id, ctx.family_id, sl.food_id, sl.quantity
    from public.shopping_list sl
   where sl.family_id = ctx.family_id and sl.in_cart
  on conflict (owner_id, food_id)
  do update set
    quantity = public.inventory.quantity + excluded.quantity,
    family_id = excluded.family_id;

  insert into public.inventory_additions (
    family_id, food_id, quantity, added_at, added_by, source, source_ref
  )
  select ctx.family_id, sl.food_id, sl.quantity, now(), ctx.user_id, 'shopping', sl.id::text
    from public.shopping_list sl
   where sl.family_id = ctx.family_id and sl.in_cart
  on conflict do nothing;

  insert into public.purchases (
    owner_id, shopper_id, family_id, food_id, quantity, price_at_purchase, purchased_at
  )
  select
    ctx.anchor_owner_id,
    ctx.user_id,
    ctx.family_id,
    sl.food_id,
    sl.quantity,
    f.price,
    now()
  from public.shopping_list sl
  join public.foods f on f.id = sl.food_id
  where sl.family_id = ctx.family_id and sl.in_cart;

  get diagnostics purchased_count = row_count;
  delete from public.shopping_list where family_id = ctx.family_id and in_cart;
  return purchased_count;
end;
$$;

create or replace function public.set_family_food_unit_qty(
  p_session_token text,
  p_food_id uuid,
  p_unit_qty text
)
returns text
language plpgsql
security definer
set search_path = public, app_private
as $$
declare
  ctx record;
  clean_unit_qty text := btrim(coalesce(p_unit_qty, ''));
begin
  select * into ctx from app_private.session_context(p_session_token);
  if ctx.family_id is null then
    raise exception 'User is not assigned to a family' using errcode = '42501';
  end if;
  if char_length(clean_unit_qty) not between 1 and 60 then
    raise exception 'Invalid product weight' using errcode = '22023';
  end if;

  update public.foods
     set unit_qty = clean_unit_qty, updated_at = now()
   where id = p_food_id;
  if not found then
    raise exception 'Product not found' using errcode = 'P0002';
  end if;
  return clean_unit_qty;
end;
$$;

alter table public.inventory_additions enable row level security;
revoke all on public.inventory_additions from anon, authenticated;

revoke all on function public.list_family_inventory_additions(text) from public;
revoke all on function public.set_family_food_unit_qty(text, uuid, text) from public;
grant execute on function public.list_family_inventory_additions(text) to anon, authenticated;
grant execute on function public.set_family_food_unit_qty(text, uuid, text) to anon, authenticated;

commit;
