begin;

create table if not exists public.site_activity (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  actor_user_id uuid references public.users(id) on delete set null,
  family_id uuid references public.families(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  details jsonb not null default '{}'::jsonb
);

create index if not exists site_activity_date_idx
  on public.site_activity (occurred_at desc, id desc);
create index if not exists site_activity_family_date_idx
  on public.site_activity (family_id, occurred_at desc, id desc);

create or replace function app_private.session_context(p_session_token text)
returns table (
  user_id uuid,
  username text,
  app_role text,
  is_admin boolean,
  family_id uuid,
  family_name text,
  member_role text,
  anchor_owner_id uuid,
  expires_at timestamptz,
  needs_password_setup boolean
)
language plpgsql
security definer
set search_path = public, app_private, extensions
as $$
declare
  resolved_user_id uuid;
begin
  select s.user_id into resolved_user_id
    from public.sessions s
   where s.token::text = p_session_token
     and s.expires_at > now()
   limit 1;

  if resolved_user_id is null then
    raise exception 'Invalid or expired session' using errcode = '42501';
  end if;

  perform set_config('app.actor_user_id', resolved_user_id::text, true);

  return query
  select
    u.id,
    u.username::text,
    u.role::text,
    u.is_admin,
    fm.family_id,
    f.name::text,
    fm.member_role::text,
    f.created_by,
    s.expires_at,
    (u.password_hash is null)
  from public.sessions s
  join public.users u on u.id = s.user_id
  left join public.family_members fm on fm.user_id = u.id
  left join public.families f on f.id = fm.family_id
  where s.token::text = p_session_token
    and s.user_id = resolved_user_id
    and s.expires_at > now()
  limit 1;
end;
$$;

revoke all on function app_private.session_context(text) from public, anon, authenticated;

create or replace function app_private.capture_site_activity()
returns trigger
language plpgsql
security definer
set search_path = public, app_private
as $$
declare
  row_data jsonb;
  actor_text text;
  actor_id uuid;
  activity_family_id uuid;
  activity_entity_id text;
  safe_details jsonb;
begin
  if tg_op = 'DELETE' then
    row_data := to_jsonb(old);
  else
    row_data := to_jsonb(new);
  end if;

  actor_text := nullif(current_setting('app.actor_user_id', true), '');
  if actor_text ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' then
    actor_id := actor_text::uuid;
  else
    actor_text := coalesce(
      row_data->>'author_id', row_data->>'added_by', row_data->>'shopper_id',
      row_data->>'actor_user_id', row_data->>'created_by', row_data->>'user_id',
      row_data->>'owner_id'
    );
    if actor_text ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' then
      actor_id := actor_text::uuid;
    end if;
  end if;

  if coalesce(row_data->>'family_id', '') ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' then
    activity_family_id := (row_data->>'family_id')::uuid;
  elsif tg_table_name = 'families' and coalesce(row_data->>'id', '') ~* '^[0-9a-f-]{36}$' then
    activity_family_id := (row_data->>'id')::uuid;
  elsif actor_id is not null then
    select fm.family_id into activity_family_id
      from public.family_members fm
     where fm.user_id = actor_id
     limit 1;
  end if;

  activity_entity_id := coalesce(
    nullif(row_data->>'id', ''),
    nullif(row_data->>'food_id', ''),
    nullif(row_data->>'user_id', '')
  );

  safe_details := jsonb_strip_nulls(jsonb_build_object(
    'name', row_data->>'name',
    'username', row_data->>'username',
    'role', row_data->>'role',
    'member_role', row_data->>'member_role',
    'food_id', row_data->>'food_id',
    'quantity', row_data->>'quantity',
    'rating', row_data->>'rating',
    'in_cart', row_data->>'in_cart',
    'source', row_data->>'source',
    'body', left(row_data->>'body', 120),
    'action', row_data->>'action',
    'entity_type', row_data->>'entity_type'
  ));

  insert into public.site_activity (
    occurred_at, actor_user_id, family_id, action, entity_type, entity_id, details
  ) values (
    now(), actor_id, activity_family_id, lower(tg_op), tg_table_name, activity_entity_id, safe_details
  );

  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

do $$
declare
  target_table text;
begin
  foreach target_table in array array[
    'users', 'sessions', 'families', 'family_members', 'foods', 'inventory',
    'inventory_additions', 'shopping_list', 'shopping_notes', 'ratings',
    'purchases', 'imported_receipts', 'push_subscriptions', 'admin_audit_log'
  ]
  loop
    if to_regclass('public.' || target_table) is not null then
      execute format('drop trigger if exists capture_site_activity on public.%I', target_table);
      execute format(
        'create trigger capture_site_activity after insert or update or delete on public.%I for each row execute function app_private.capture_site_activity()',
        target_table
      );
    end if;
  end loop;
end;
$$;

insert into public.site_activity (occurred_at, actor_user_id, family_id, action, entity_type, entity_id, details)
select f.created_at, f.created_by, f.id, 'insert', 'families', f.id::text,
       jsonb_build_object('name', f.name)
  from public.families f
 where not exists (
   select 1 from public.site_activity a
    where a.entity_type = 'families' and a.entity_id = f.id::text and a.action = 'insert'
 );

insert into public.site_activity (occurred_at, actor_user_id, family_id, action, entity_type, entity_id, details)
select fm.joined_at, fm.user_id, fm.family_id, 'insert', 'family_members', fm.user_id::text,
       jsonb_build_object('member_role', fm.member_role)
  from public.family_members fm
 where not exists (
   select 1 from public.site_activity a
    where a.entity_type = 'family_members' and a.entity_id = fm.user_id::text and a.action = 'insert'
 );

insert into public.site_activity (occurred_at, actor_user_id, family_id, action, entity_type, entity_id, details)
select f.created_at, f.created_by, fm.family_id, 'insert', 'foods', f.id::text,
       jsonb_build_object('name', f.name)
  from public.foods f
  left join public.family_members fm on fm.user_id = f.created_by
 where not exists (
   select 1 from public.site_activity a
    where a.entity_type = 'foods' and a.entity_id = f.id::text and a.action = 'insert'
 );

insert into public.site_activity (occurred_at, actor_user_id, family_id, action, entity_type, entity_id, details)
select ia.added_at, ia.added_by, ia.family_id, 'insert', 'inventory_additions', ia.id::text,
       jsonb_build_object('food_id', ia.food_id, 'quantity', ia.quantity, 'source', ia.source)
  from public.inventory_additions ia
 where not exists (
   select 1 from public.site_activity a
    where a.entity_type = 'inventory_additions' and a.entity_id = ia.id::text and a.action = 'insert'
 );

insert into public.site_activity (occurred_at, actor_user_id, family_id, action, entity_type, entity_id, details)
select p.purchased_at, p.shopper_id, p.family_id, 'insert', 'purchases', p.id::text,
       jsonb_build_object('food_id', p.food_id, 'quantity', p.quantity)
  from public.purchases p
 where not exists (
   select 1 from public.site_activity a
    where a.entity_type = 'purchases' and a.entity_id = p.id::text and a.action = 'insert'
 );

insert into public.site_activity (occurred_at, actor_user_id, family_id, action, entity_type, entity_id, details)
select n.created_at, n.author_id, n.family_id, 'insert', 'shopping_notes', n.id::text,
       jsonb_build_object('body', left(n.body, 120))
  from public.shopping_notes n
 where not exists (
   select 1 from public.site_activity a
    where a.entity_type = 'shopping_notes' and a.entity_id = n.id::text and a.action = 'insert'
 );

create or replace function public.admin_dashboard_summary(p_session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, app_private
as $$
declare
  ctx record;
begin
  select * into ctx from app_private.session_context(p_session_token);
  if not ctx.is_admin then
    raise exception 'Administrator access required' using errcode = '42501';
  end if;

  return jsonb_build_object(
    'families', (select count(*) from public.families),
    'users', (select count(*) from public.users),
    'products', (select count(*) from public.foods),
    'pending_requests', (select count(*) from public.shopping_list),
    'purchases_7d', (select count(*) from public.purchases where purchased_at >= now() - interval '7 days'),
    'active_users_24h', (
      select count(distinct actor_user_id) from public.site_activity
       where occurred_at >= now() - interval '24 hours' and actor_user_id is not null
    )
  );
end;
$$;

create or replace function public.admin_list_families(p_session_token text)
returns table (
  family_id uuid,
  family_name text,
  invite_code text,
  member_count bigint,
  pending_requests bigint,
  inventory_products bigint,
  purchases_7d bigint,
  last_activity timestamptz
)
language plpgsql
security definer
set search_path = public, app_private
as $$
declare
  ctx record;
begin
  select * into ctx from app_private.session_context(p_session_token);
  if not ctx.is_admin then
    raise exception 'Administrator access required' using errcode = '42501';
  end if;

  return query
  select
    f.id,
    f.name::text,
    f.invite_code::text,
    (select count(*) from public.family_members fm where fm.family_id = f.id),
    (select count(*) from public.shopping_list sl where sl.family_id = f.id),
    (select count(*) from public.inventory i where i.family_id = f.id and i.quantity > 0),
    (select count(*) from public.purchases p where p.family_id = f.id and p.purchased_at >= now() - interval '7 days'),
    (select max(a.occurred_at) from public.site_activity a where a.family_id = f.id)
  from public.families f
  order by coalesce((select max(a.occurred_at) from public.site_activity a where a.family_id = f.id), f.created_at) desc;
end;
$$;

create or replace function public.admin_list_activity(
  p_session_token text,
  p_family_id uuid default null,
  p_limit integer default 100,
  p_before_id bigint default null
)
returns table (
  activity_id bigint,
  occurred_at timestamptz,
  actor_user_id uuid,
  actor_name text,
  family_id uuid,
  family_name text,
  action text,
  entity_type text,
  entity_id text,
  details jsonb
)
language plpgsql
security definer
set search_path = public, app_private
as $$
declare
  ctx record;
begin
  select * into ctx from app_private.session_context(p_session_token);
  if not ctx.is_admin then
    raise exception 'Administrator access required' using errcode = '42501';
  end if;

  return query
  select
    a.id,
    a.occurred_at,
    a.actor_user_id,
    coalesce(u.username, 'מערכת')::text,
    a.family_id,
    coalesce(f.name, 'כללי')::text,
    a.action,
    a.entity_type,
    a.entity_id,
    a.details || jsonb_strip_nulls(jsonb_build_object(
      'food_name', (
        select food.name from public.foods food
         where food.id::text = a.details->>'food_id'
         limit 1
      )
    ))
  from public.site_activity a
  left join public.users u on u.id = a.actor_user_id
  left join public.families f on f.id = a.family_id
  where (p_family_id is null or a.family_id = p_family_id)
    and (p_before_id is null or a.id < p_before_id)
  order by a.id desc
  limit least(greatest(coalesce(p_limit, 100), 1), 200);
end;
$$;

do $$
declare
  admin_id uuid;
begin
  select id into admin_id from public.users where lower(btrim(username)) = 'admin' limit 1;
  if admin_id is null then
    admin_id := gen_random_uuid();
    insert into public.users (
      id, username, email, password_hash, role, shops_for_user_id, is_admin,
      failed_login_attempts, locked_until
    ) values (
      admin_id, 'admin', null, '$2a$12$rdj.goiwuvBa7D9fy..x6O70u8BvA5XxwIEaktz41R/c/YRCL1Ag6', 'owner', null, true, 0, null
    );
  elsif not exists (select 1 from public.users where id = admin_id and is_admin) then
    raise exception 'The username admin already belongs to a non-admin account';
  end if;
end;
$$;

alter table public.site_activity enable row level security;
revoke all on public.site_activity from anon, authenticated;
revoke all on function public.admin_dashboard_summary(text) from public;
revoke all on function public.admin_list_families(text) from public;
revoke all on function public.admin_list_activity(text, uuid, integer, bigint) from public;
grant execute on function public.admin_dashboard_summary(text) to anon, authenticated;
grant execute on function public.admin_list_families(text) to anon, authenticated;
grant execute on function public.admin_list_activity(text, uuid, integer, bigint) to anon, authenticated;

commit;
